---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: run-image-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-image-pipelinerun
  labels:
    app.kubernetes.io/description: A PipelineRun configured to specify an explicit run image.
spec:
  pipelineRef:
    name: buildpacks
  params:
    - name: BUILDER_IMAGE
      value: docker.io/cnbs/sample-builder:bionic@sha256:6c03dd604503b59820fd15adbc65c0a077a47e31d404a3dcad190f3179e920b5
    - name: TRUST_BUILDER
      value: "true"
    - name: APP_IMAGE
      value: <IMAGE_NAME>
    - name: SOURCE_URL
      value: https://github.com/buildpacks/samples
    - name: SOURCE_SUBPATH
      value: apps/ruby-bundler
    - name: RUN_IMAGE
      value: docker.io/cnbs/sample-stack-run:bionic@sha256:766617895a96c9cdc58fa604468328f6918a13f5c225fbe267b37df9dce40fda
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: run-image-ws-pvc
    # NOTE: Pipeline hangs if optional cache workspace is missing so we provide an empty directory
    - name: cache-ws
      emptyDir: {}
